# ============================================================
# Module: Report Generator
# Auto-generate PDF/HTML reports
# ============================================================

generate_report <- function(data, stats, report_type = "html") {
  timestamp <- format(Sys.time(), "%Y%m%d_%H%M%S")
  filename <- paste0("report_", timestamp, ".", report_type)
  filepath <- file.path(REPORT_DIR, filename)

  # Create Rmd content
  rmd_content <- create_report_rmd(data, stats)

  # Write Rmd file
  rmd_path <- file.path(REPORT_DIR, paste0("report_", timestamp, ".Rmd"))
  writeLines(rmd_content, rmd_path)

  # Render report
  tryCatch({
    rmarkdown::render(
      rmd_path,
      output_file = filename,
      output_dir = REPORT_DIR,
      quiet = TRUE
    )
    return(list(success = TRUE, filepath = filepath, message = "Laporan berhasil dibuat"))
  }, error = function(e) {
    return(list(success = FALSE, message = paste("Error:", e$message)))
  })
}

create_report_rmd <- function(data, stats) {
  paste0('
---
title: "Data Analysis Report"
date: "', format(Sys.Date(), "%B %d, %Y"), '"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(DT)
library(ggplot2)
```

## Data Summary

- **Rows:** ', nrow(data), '
- **Columns:** ', ncol(data), '
- **Missing Values:** ', sum(is.na(data)), '

## Data Preview

```{r}
DT::datatable(head(data, 20))
```

## Descriptive Statistics

```{r}
stats_df <- data.frame(
  Column = names(stats)[sapply(stats, is.list)],
  Mean = sapply(stats[sapply(stats, is.list)], function(x) round(x$mean, 4)),
  Median = sapply(stats[sapply(stats, is.list)], function(x) round(x$median, 4)),
  SD = sapply(stats[sapply(stats, is.list)], function(x) round(x$sd, 4)),
  Min = sapply(stats[sapply(stats, is.list)], function(x) round(x$min, 4)),
  Max = sapply(stats[sapply(stats, is.list)], function(x) round(x$max, 4))
)
DT::datatable(stats_df)
```

## Visualizations

```{r fig.width=10, fig.height=6}
numeric_cols <- names(data)[sapply(data, is.numeric)]
if (length(numeric_cols) >= 2) {
  pairs(data[, numeric_cols[1:min(4, length(numeric_cols))]], 
        main = "Pairwise Scatter Plots", pch = 19, col = rgb(0.1, 0.4, 0.7, 0.5))
}
```

---
*Report generated by Intelligent Data Analytics Dashboard*
')
}
